server:
  port: 9002
  
  
spring:
  application:
    name: nacos-provider9002
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848    #配置nacos的地址
    
    
management:
  endpoints:
    web:
      exposure:
        include: "*"    