server:
  port: 9411
  
  
spring:
  application:
    name: cloud-stream-provider
  zipkin:    base-url: http://localhost:9411
  sleuth:    sampler:      probability: 1    #采集率介于0到1之间，1表示全部采集
    
eureka:
  client:
    #表示能否将自己注册到eureka服务中，默认为true
    register-with-eureka: true
    fetch-registry: true          #是否从eureka服务端抓取已有的注册信息，设置为true，才能配合ribbon实现负载均衡
    serviceUrl:
      defaultZone: http://eureka6001.cn:6001/eureka/,http://eureka6002.cn:6002/eureka/
      #defaultZone: http://127.0.0.1:6001/eureka/
  instance:
    lease-renewal-interval-in-seconds: 2     #设置心跳的时间间隔，默认是30秒
    lease-expiration-duration-in-seconds: 5     #设置现在超过了5秒的间隔，默认90秒
    instance-id: provider9411
    prefer-ip-address: true