spring:
  application:
    name: springfox-swagger
server:
  port: 8008
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox_swagger_3.0整合Demo
  try-host: http://localhost:${server.port}